services:

  postgres:
    image: postgres:16
    container_name: bookings-postgres
    restart: always
    environment:
      POSTGRES_DB: bookings-project-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Senai@127
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: bookings-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bookings-project-db
      DB_USERNAME: postgres
      DB_PASSWORD: Senai@127
      PORT: 8080
      JWT_SECRET: bookingsProject2026
      JWT_EXPIRATION: 3000
      JWT_ISSUER: Bookings Project API
      MIGRATIONS_ENABLED: true
      HIBERNATE_DDL: validate
      TZ: America/Sao_Paulo

volumes:
  postgres_data: