version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: bookings-postgres
    restart: always
    environment:
      POSTGRES_DB: bookings-project-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Senai@127
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: bookings-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: bookings-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: bookings-kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: bookings-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  api:
    container_name: bookings-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bookings-project-db
      DB_USERNAME: postgres
      DB_PASSWORD: Senai@127
      PORT: 8080
      JWT_SECRET: bookingsProject2026
      JWT_EXPIRATION: 3000
      JWT_ISSUER: Bookings Project API
      MIGRATIONS_ENABLED: true
      HIBERNATE_DDL: validate
      TZ: America/Sao_Paulo

volumes:
  postgres_data: