package br.richard.bookingsproject.errors;

public enum ExceptionCode {
    API_FIELDS_INVALID,
    INTERNAL_SERVER_ERROR,
    ENTITY_NOT_FOUND,
    DUPLICATED_RESOURCE,
    EMAIL_NOT_SENT,
    UNAUTHORIZED,
    AUTHENTICATION_TOKEN_CREATION_ERROR,
    FORBIDDEN,
    EXPIRED_TOKEN,
    USED_TOKEN,
    BAD_CREDENTIALS,
    INVALID_REQUEST_EXCEPTION,
    JSON_MAPPING_ERROR,
    EMAIL_NOT_VALIDATED,
    INVALID_PASSWORD_RECOVERY_CODE,
    NOT_AVAILABLE_DATE_EXCEPTION,
    USER_HAS_RESERVATIONS,
    RENTAL_TYPE_HAS_RESERVATIONS,
    INVALID_RESERVATION_DATE
}